### ISSUE TITLE
Unexpected `impl` in type path

### ISSUE THREAD

**Issue by athre0z** [alexcrichton/rustc-demangle#43]
The library (`v0.1.18`) currently demangles

```
_ZN4core3num21_$LT$impl$u20$u32$GT$12wrapping_add17hc54a7f304006bc88E
```

to

```
core::num::<impl u32>::wrapping_add
```

The `impl` token seems to be unexpected here. Tested via `rustfilt`.

**Comment by alexcrichton** [comment]
Thanks for the report! I think though the demangling here is correct in that `impl` is in the symbol, this may be a better bug for rustc to omit it if you think it shouldn't be there?

**Comment by athre0z** [comment]
Oh yeah, good point. I didn't even spot the literal "impl" in all the mangled gibberish. Looks like it's a rustc issue then. Thanks!

**Comment by eddyb** [comment]
That's the expected mangling for an inherent `impl`, tho in other cases you might not see this because of a special case (so that you get e.g. `alloc::vec::Vec::new` instead of `alloc::vec::<impl Vec<T>>::new`).

The `legacy` mangling is unlikely to change for the time being, and it's limited by being mostly just a string.
By contrast, the `v0` mangling includes both the path to the `impl` itself, and the `Self` type, so the demangler can choose what to show (tho `rustc-demangle` doesn't have a toggle for "show everything" yet).

You can see the difference here: https://godbolt.org/z/M65ds3
||demangled|mangled|
|-:|-|-|
|`legacy`|`core::num::<impl u32>::wrapping_add`|`_ZN4core3num21_$LT$impl$u20$u32$GT$12wrapping_add17hc594d9392171a081E`|
|`v0`|`<u32>::wrapping_add`|`_RNvMs6_NtCs3p84KrD9aKt_4core3numm12wrapping_addCsbDqzXfLQacH_7example`|

<hr/>

Let's do a deep dive! In the `v0` mangling `Ms6_NtCs3p84KrD9aKt_4core3numm` parses as such:
```
M(s6_, N(t, C(s3p84KrD9aKt_, 4core), 3num), m)
```
You can already see that `core::num` is mentioned there, but we can do better (I did the below annotation by hand, but it would be really cool if we had a tool that did something similar):
```rust
InherentImpl {                  // M
  disambiguator: 7,             // s6_
  parent: PathSegment {         // N
    ns: 't',                    // t
    parent: Crate {             // C
      hash: 0x27a9f88932ca0ab3, // s3p84KrD9aKt_
      name: "core",             // 4core
    },
    name: "num",                // 3num
  },
  self_type: u32,               // m
}
```

So `core[27a9f88932ca0ab3]::num::{impl#7 u32}` with hashes, or `core::num::{impl#7 u32}` without (this isn't a notation used anywhere else, but it's the most straightforward I can come up with for demonstration purposes).

**Comment by athre0z** [comment]
Thanks for the detailed explanation, good to know! 👍
